/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/auth/LoginPage': RouteRecordInfo<
      '/auth/LoginPage',
      '/auth/LoginPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/Register': RouteRecordInfo<
      '/auth/Register',
      '/auth/Register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/checkout/InformationPage': RouteRecordInfo<
      '/checkout/InformationPage',
      '/checkout/InformationPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/checkout/PaymentPage': RouteRecordInfo<
      '/checkout/PaymentPage',
      '/checkout/PaymentPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/checkout/ShippingPage': RouteRecordInfo<
      '/checkout/ShippingPage',
      '/checkout/ShippingPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/HomePage': RouteRecordInfo<
      '/home/HomePage',
      '/home/HomePage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/NotFound': RouteRecordInfo<
      '/NotFound',
      '/NotFound',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/products/MyProductsPage': RouteRecordInfo<
      '/products/MyProductsPage',
      '/products/MyProductsPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/products/ProductsInfoPage': RouteRecordInfo<
      '/products/ProductsInfoPage',
      '/products/ProductsInfoPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/products/ProductsPage': RouteRecordInfo<
      '/products/ProductsPage',
      '/products/ProductsPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile/profile-products/FavoriteProductsPage': RouteRecordInfo<
      '/profile/profile-products/FavoriteProductsPage',
      '/profile/profile-products/FavoriteProductsPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile/profile-products/ProductsCartPage': RouteRecordInfo<
      '/profile/profile-products/ProductsCartPage',
      '/profile/profile-products/ProductsCartPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile/ProfilePage': RouteRecordInfo<
      '/profile/ProfilePage',
      '/profile/ProfilePage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/auth/LoginPage.vue': {
      routes:
        | '/auth/LoginPage'
      views:
        | never
    }
    'src/pages/auth/Register.vue': {
      routes:
        | '/auth/Register'
      views:
        | never
    }
    'src/pages/checkout/InformationPage.vue': {
      routes:
        | '/checkout/InformationPage'
      views:
        | never
    }
    'src/pages/checkout/PaymentPage.vue': {
      routes:
        | '/checkout/PaymentPage'
      views:
        | never
    }
    'src/pages/checkout/ShippingPage.vue': {
      routes:
        | '/checkout/ShippingPage'
      views:
        | never
    }
    'src/pages/home/HomePage.vue': {
      routes:
        | '/home/HomePage'
      views:
        | never
    }
    'src/pages/NotFound.vue': {
      routes:
        | '/NotFound'
      views:
        | never
    }
    'src/pages/products/MyProductsPage.vue': {
      routes:
        | '/products/MyProductsPage'
      views:
        | never
    }
    'src/pages/products/ProductsInfoPage.vue': {
      routes:
        | '/products/ProductsInfoPage'
      views:
        | never
    }
    'src/pages/products/ProductsPage.vue': {
      routes:
        | '/products/ProductsPage'
      views:
        | never
    }
    'src/pages/profile/profile-products/FavoriteProductsPage.vue': {
      routes:
        | '/profile/profile-products/FavoriteProductsPage'
      views:
        | never
    }
    'src/pages/profile/profile-products/ProductsCartPage.vue': {
      routes:
        | '/profile/profile-products/ProductsCartPage'
      views:
        | never
    }
    'src/pages/profile/ProfilePage.vue': {
      routes:
        | '/profile/ProfilePage'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
